// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckGameDir() {
  return window['go']['editor']['App']['CheckGameDir']();
}

export function ChooseGameDir() {
  return window['go']['editor']['App']['ChooseGameDir']();
}

export function ClearPlayer(arg1, arg2) {
  return window['go']['editor']['App']['ClearPlayer'](arg1, arg2);
}

export function ClearRegion(arg1, arg2, arg3) {
  return window['go']['editor']['App']['ClearRegion'](arg1, arg2, arg3);
}

export function CopyRegion(arg1) {
  return window['go']['editor']['App']['CopyRegion'](arg1);
}

export function CreatePlots(arg1, arg2) {
  return window['go']['editor']['App']['CreatePlots'](arg1, arg2);
}

export function CurrentMapPath() {
  return window['go']['editor']['App']['CurrentMapPath']();
}

export function ExportImage(arg1) {
  return window['go']['editor']['App']['ExportImage'](arg1);
}

export function FixProblems(arg1) {
  return window['go']['editor']['App']['FixProblems'](arg1);
}

export function GenerateTerrain(arg1) {
  return window['go']['editor']['App']['GenerateTerrain'](arg1);
}

export function GetCities() {
  return window['go']['editor']['App']['GetCities']();
}

export function GetCivilizations() {
  return window['go']['editor']['App']['GetCivilizations']();
}

export function GetClipboard() {
  return window['go']['editor']['App']['GetClipboard']();
}

export function GetConfig() {
  return window['go']['editor']['App']['GetConfig']();
}

export function GetGame() {
  return window['go']['editor']['App']['GetGame']();
}

export function GetLanguages() {
  return window['go']['editor']['App']['GetLanguages']();
}

export function GetMapInfo() {
  return window['go']['editor']['App']['GetMapInfo']();
}

export function GetMapProps() {
  return window['go']['editor']['App']['GetMapProps']();
}

export function GetMapStats() {
  return window['go']['editor']['App']['GetMapStats']();
}

export function GetMapView() {
  return window['go']['editor']['App']['GetMapView']();
}

export function GetModsList() {
  return window['go']['editor']['App']['GetModsList']();
}

export function GetOptions() {
  return window['go']['editor']['App']['GetOptions']();
}

export function GetPlayers() {
  return window['go']['editor']['App']['GetPlayers']();
}

export function GetPlot(arg1, arg2) {
  return window['go']['editor']['App']['GetPlot'](arg1, arg2);
}

export function GetSigns() {
  return window['go']['editor']['App']['GetSigns']();
}

export function GetTeams() {
  return window['go']['editor']['App']['GetTeams']();
}

export function GetUnits() {
  return window['go']['editor']['App']['GetUnits']();
}

export function GetVersion() {
  return window['go']['editor']['App']['GetVersion']();
}

export function GetWorldSizes() {
  return window['go']['editor']['App']['GetWorldSizes']();
}

export function HasMap() {
  return window['go']['editor']['App']['HasMap']();
}

export function HistoryState() {
  return window['go']['editor']['App']['HistoryState']();
}

export function LaunchGame() {
  return window['go']['editor']['App']['LaunchGame']();
}

export function LoadGameXML() {
  return window['go']['editor']['App']['LoadGameXML']();
}

export function NewMap() {
  return window['go']['editor']['App']['NewMap']();
}

export function OpenMap(arg1) {
  return window['go']['editor']['App']['OpenMap'](arg1);
}

export function OpenMapDialog() {
  return window['go']['editor']['App']['OpenMapDialog']();
}

export function PaintPlots(arg1) {
  return window['go']['editor']['App']['PaintPlots'](arg1);
}

export function PasteRegion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['editor']['App']['PasteRegion'](arg1, arg2, arg3, arg4, arg5);
}

export function PlaceStarts(arg1) {
  return window['go']['editor']['App']['PlaceStarts'](arg1);
}

export function Redo() {
  return window['go']['editor']['App']['Redo']();
}

export function ReplaceType(arg1, arg2, arg3) {
  return window['go']['editor']['App']['ReplaceType'](arg1, arg2, arg3);
}

export function ResetGameXML() {
  return window['go']['editor']['App']['ResetGameXML']();
}

export function ResizeMap(arg1, arg2, arg3, arg4) {
  return window['go']['editor']['App']['ResizeMap'](arg1, arg2, arg3, arg4);
}

export function SaveMap(arg1) {
  return window['go']['editor']['App']['SaveMap'](arg1);
}

export function SaveMapAs() {
  return window['go']['editor']['App']['SaveMapAs']();
}

export function SearchMap(arg1) {
  return window['go']['editor']['App']['SearchMap'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['editor']['App']['SetConfig'](arg1);
}

export function SetGame(arg1) {
  return window['go']['editor']['App']['SetGame'](arg1);
}

export function SetMapProps(arg1) {
  return window['go']['editor']['App']['SetMapProps'](arg1);
}

export function SetPlayerStart(arg1, arg2, arg3) {
  return window['go']['editor']['App']['SetPlayerStart'](arg1, arg2, arg3);
}

export function SetPlayers(arg1) {
  return window['go']['editor']['App']['SetPlayers'](arg1);
}

export function SetPlot(arg1) {
  return window['go']['editor']['App']['SetPlot'](arg1);
}

export function SetPlotSigns(arg1, arg2, arg3) {
  return window['go']['editor']['App']['SetPlotSigns'](arg1, arg2, arg3);
}

export function SetTeams(arg1) {
  return window['go']['editor']['App']['SetTeams'](arg1);
}

export function SwapPlayers(arg1, arg2) {
  return window['go']['editor']['App']['SwapPlayers'](arg1, arg2);
}

export function TranslateKey(arg1) {
  return window['go']['editor']['App']['TranslateKey'](arg1);
}

export function Undo() {
  return window['go']['editor']['App']['Undo']();
}

export function ValidateMap() {
  return window['go']['editor']['App']['ValidateMap']();
}

export function WriteConsole(arg1) {
  return window['go']['editor']['App']['WriteConsole'](arg1);
}

export function XmlReady() {
  return window['go']['editor']['App']['XmlReady']();
}
