// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {editor} from '../models';

export function CheckGameDir():Promise<string>;

export function CurrentMapPath():Promise<string>;

export function GetCalendarOptions():Promise<Array<editor.EnumOption>>;

export function GetConfig():Promise<editor.Config>;

export function GetEraOptions():Promise<Array<editor.EnumOption>>;

export function GetForceControlOptions():Promise<Array<editor.EnumOption>>;

export function GetGame():Promise<editor.Game|null>;

export function GetGameOptionOptions():Promise<Array<editor.EnumOption>>;

export function GetMPOptionOptions():Promise<Array<editor.EnumOption>>;

export function GetMapInfo():Promise<editor.MapInfo|null>;

export function GetModsList():Promise<Array<string>>;

export function GetPlayers():Promise<Array<editor.Player>|null>;

export function GetSpeedOptions():Promise<Array<editor.EnumOption>>;

export function GetTeams():Promise<Array<editor.Team>|null>;

export function GetVictoryOptions():Promise<Array<editor.EnumOption>>;

export function HasMap():Promise<boolean>;

export function LaunchGame():Promise<void>;

export function LoadGameXML():Promise<void>;

export function NewMap():Promise<void>;

export function OpenMap(arg1:string):Promise<void>;

export function OpenMapDialog():Promise<string>;

export function SaveMap(arg1:string):Promise<string>;

export function SetConfig(arg1:editor.Config):Promise<void>;

export function SetGame(arg1:editor.Game):Promise<void>;

export function SetPlayers(arg1:Array<editor.Player>):Promise<void>;

export function SetTeams(arg1:Array<editor.Team>):Promise<void>;

export function TranslateKey(arg1:string):Promise<string>;

export function WriteConsole(arg1:string):Promise<void>;

export function XmlReady():Promise<boolean>;
