// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckGameDir() {
  return window['go']['editor']['App']['CheckGameDir']();
}

export function CurrentMapPath() {
  return window['go']['editor']['App']['CurrentMapPath']();
}

export function GetCalendarOptions() {
  return window['go']['editor']['App']['GetCalendarOptions']();
}

export function GetConfig() {
  return window['go']['editor']['App']['GetConfig']();
}

export function GetEraOptions() {
  return window['go']['editor']['App']['GetEraOptions']();
}

export function GetForceControlOptions() {
  return window['go']['editor']['App']['GetForceControlOptions']();
}

export function GetGame() {
  return window['go']['editor']['App']['GetGame']();
}

export function GetGameOptionOptions() {
  return window['go']['editor']['App']['GetGameOptionOptions']();
}

export function GetMPOptionOptions() {
  return window['go']['editor']['App']['GetMPOptionOptions']();
}

export function GetMapInfo() {
  return window['go']['editor']['App']['GetMapInfo']();
}

export function GetModsList() {
  return window['go']['editor']['App']['GetModsList']();
}

export function GetPlayers() {
  return window['go']['editor']['App']['GetPlayers']();
}

export function GetSpeedOptions() {
  return window['go']['editor']['App']['GetSpeedOptions']();
}

export function GetTeams() {
  return window['go']['editor']['App']['GetTeams']();
}

export function GetVictoryOptions() {
  return window['go']['editor']['App']['GetVictoryOptions']();
}

export function HasMap() {
  return window['go']['editor']['App']['HasMap']();
}

export function LaunchGame() {
  return window['go']['editor']['App']['LaunchGame']();
}

export function LoadGameXML() {
  return window['go']['editor']['App']['LoadGameXML']();
}

export function NewMap() {
  return window['go']['editor']['App']['NewMap']();
}

export function OpenMap(arg1) {
  return window['go']['editor']['App']['OpenMap'](arg1);
}

export function OpenMapDialog() {
  return window['go']['editor']['App']['OpenMapDialog']();
}

export function SaveMap(arg1) {
  return window['go']['editor']['App']['SaveMap'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['editor']['App']['SetConfig'](arg1);
}

export function SetGame(arg1) {
  return window['go']['editor']['App']['SetGame'](arg1);
}

export function SetPlayers(arg1) {
  return window['go']['editor']['App']['SetPlayers'](arg1);
}

export function SetTeams(arg1) {
  return window['go']['editor']['App']['SetTeams'](arg1);
}

export function TranslateKey(arg1) {
  return window['go']['editor']['App']['TranslateKey'](arg1);
}

export function WriteConsole(arg1) {
  return window['go']['editor']['App']['WriteConsole'](arg1);
}

export function XmlReady() {
  return window['go']['editor']['App']['XmlReady']();
}
