// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckGameDir() {
  return window['go']['editor']['App']['CheckGameDir']();
}

export function ChooseGameDir() {
  return window['go']['editor']['App']['ChooseGameDir']();
}

export function CurrentMapPath() {
  return window['go']['editor']['App']['CurrentMapPath']();
}

export function GetCivilizations() {
  return window['go']['editor']['App']['GetCivilizations']();
}

export function GetConfig() {
  return window['go']['editor']['App']['GetConfig']();
}

export function GetGame() {
  return window['go']['editor']['App']['GetGame']();
}

export function GetMapInfo() {
  return window['go']['editor']['App']['GetMapInfo']();
}

export function GetModsList() {
  return window['go']['editor']['App']['GetModsList']();
}

export function GetOptions() {
  return window['go']['editor']['App']['GetOptions']();
}

export function GetPlayers() {
  return window['go']['editor']['App']['GetPlayers']();
}

export function GetTeams() {
  return window['go']['editor']['App']['GetTeams']();
}

export function HasMap() {
  return window['go']['editor']['App']['HasMap']();
}

export function LaunchGame() {
  return window['go']['editor']['App']['LaunchGame']();
}

export function LoadGameXML() {
  return window['go']['editor']['App']['LoadGameXML']();
}

export function NewMap() {
  return window['go']['editor']['App']['NewMap']();
}

export function OpenMap(arg1) {
  return window['go']['editor']['App']['OpenMap'](arg1);
}

export function OpenMapDialog() {
  return window['go']['editor']['App']['OpenMapDialog']();
}

export function ResetGameXML() {
  return window['go']['editor']['App']['ResetGameXML']();
}

export function SaveMap(arg1) {
  return window['go']['editor']['App']['SaveMap'](arg1);
}

export function SaveMapAs() {
  return window['go']['editor']['App']['SaveMapAs']();
}

export function SetConfig(arg1) {
  return window['go']['editor']['App']['SetConfig'](arg1);
}

export function SetGame(arg1) {
  return window['go']['editor']['App']['SetGame'](arg1);
}

export function SetPlayers(arg1) {
  return window['go']['editor']['App']['SetPlayers'](arg1);
}

export function SetTeams(arg1) {
  return window['go']['editor']['App']['SetTeams'](arg1);
}

export function TranslateKey(arg1) {
  return window['go']['editor']['App']['TranslateKey'](arg1);
}

export function WriteConsole(arg1) {
  return window['go']['editor']['App']['WriteConsole'](arg1);
}

export function XmlReady() {
  return window['go']['editor']['App']['XmlReady']();
}
